<?php
// use DB;

return [
    /* Used In Revenue Report */
    'month' => [
        '1' => 'January',
        '2' => 'February',
        '3' => 'March',
        '4' => 'April',
        '5' => 'May',
        '6' => 'June',
        '7' => 'July',
        '8' => 'August',
        '9' => 'September',
        '10' => 'October',
        '11' => 'November',
        '12' => 'December',
    ],
    'type' => [
        'equal' => '=',
        'not_equal' => '!=',
        'less_than' => '<',
        'greater_than' => '>',
        'less_equal' => '<=',
        'greater_equal' => '>=',
        'like' => 'like',
        'not_like' => 'not like',
    ],
    'pagination' => 25,
    /* Cylinder No. */
    'cylinder_no' => ['1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5, '6' => 6, '7' => 7, '8' => 8, '9' => 9],
    /* used in cylinder out */
    'reason' => [
        "Engraver Fault" => "Engraver Fault",
        "Design Change" => "Design Change",
        "Damage Cylinder" => "Damage Cylinder",
        "Cylinder Verandine" => "Cylinder Verandine",
        "Sold" => "Sold",
        "Return To Customer" => "Return To Customer",
        "Re-Engraving" => "Re-Engraving",
        "Other" => "Other",
    ],
    'project_name' => "Jayshri Propack Pvt. Ltd.",
    'site_address' => "Jayshri Ln, Changodar, Gujarat 382213.",
    'rawlist' => [
        '-1' => "Ink",
        '-2' => "Adhesive",
        '-3' => "Other",
        '-4' => "Ex",
    ],
    'category' => [
        'Basic Printing' => 'Basic Printing',
        'Lamination' => 'Lamination',
        'Ink' => 'Ink',
        'Solvants(Chemicals)' => 'Solvants(Chemicals)',
        'Adhesive' => 'Adhesive',
        'Doctor Blade' => 'Doctor Blade',
        // 'Waste Cotton' => 'Waste Cotton',
        'Sellotape' => 'Sellotape',
        // 'Bamboo' => 'Bamboo',
        'Granules' => 'Granules',
        'Wastage' => 'Wastage',
        'Pouch' => 'Pouch',
        'Spout' => 'Spout',
    ],
    'po_source' => [
        "By Email" => "By Email",
        "By Call" => "By Call",
        "By WhatsApp" => "By WhatsApp",
        "By Reference" => "By Reference",
        "By Courier" => "By Courier",
        "By Application" => "By Application",
        "Other" => "Other",
    ],
    'page-width' => '75',
    'page-height' => '55',
    'margin-top' => '5',
    'margin-right' => '2',
    'margin-bottom' => '5',
    'margin-left' => '2',
    'basic_printing' => [
        "BOPP" => "BOPP",
        // "Bopp white" => "Bopp white",
        "BOPP-WHITE" => "BOPP-WHITE",
        "LDPE" => "LDPE",
        "MET" => "MET",
        "NON HST BOPP" => "NON HST BOPP",
        "PET" => "PET",
        "PLAIN BOPP" => "PLAIN BOPP",
        "PLAIN-BOPP" => "PLAIN-BOPP",
    ],
    
    'category_prefix' => [
        'Basic Printing' => 'BP',
        'Lamination' => 'LN',
        'Ink' => 'IN',
        'Solvants(Chemicals)' => 'SC',
        'Adhesive' => 'AD',
        'Doctor Blade' => 'DB',
        'Waste Cotton' => 'WC',
        'Sellotape' => 'ST',
        'Bamboo' => 'BM',
        'Granules' => 'GR',
        'Wastage' => 'WT',
    ],
    'under_group' => [
        "Bank Account"  => "Bank Account",
        "Bank OCC A/c"  => "Bank OCC A/c",
        "Bank OD A/c"   => "Bank OD A/c",
        // "Branch/Divisions"  => "Branch/Divisions",
        "Capital Account"   => "Capital Account",
        "Cash-in-hand"  => "Cash-in-hand",
        "Current Assets"    => "Current Assets",
        "Current Liabilities"   => "Current Liabilities",
        "Deposits(Asset)"   => "Deposits(Asset)",
        "Direct Expenses"   => "Direct Expenses",
        "Direct Incomes"    => "Direct Incomes",
        "Duties & Taxes"    => "Duties & Taxes",
        "Fixed Assets"  => "Fixed Assets",
        "Indirect Expenses" => "Indirect Expenses",
        "Indirect Incomes"  => "Indirect Incomes",
        "Investment"    => "Investment",
        "Loan & Advances(Asset)"    => "Loan & Advances(Asset)",
        "Loans(Liability)"  => "Loans(Liability)",
        "Misc. Expenses(ASSET)" => "Misc. Expenses(ASSET)",
        "Provision" => "Provision",
        "Purchase Account" => "Purchase Account",
        "Reserves & Surplus"    => "Reserves & Surplus",
        "Retained Earnings" => "Retained Earnings",
        "Sales Account" => "Sales Account",
        "Secured Loans" => "Secured Loans",
        "Stock-in-hand" => "Stock-in-hand",
        "Sundry Creditors"  => "Sundry Creditors",
        "Sundry Debtors"    => "Sundry Debtors",
        "Suspense A/c"  => "Suspense A/c",
        "Unsecured Loans"   => "Unsecured Loans",
        "Advanced & Receivables"    => "Advanced & Receivables",
        "Profit & Loss Account" => "Profit & Loss Account"
    ],
    'pdf' => 'limitless.pdf',
    'gst_codes' => [
        '1' => "JAMMU AND KASHMIR",
        '2'  => 'HIMACHAL PRADESH',
        '3'  => 'PUNJAB',
        '4'  => 'CHANDIGARH',
        '5'  => 'UTTARAKHAND',
        '6'  => 'HARYANA',
        '7'  => 'DELHI',
        '8'  => 'RAJASTHAN',
        '9'  => 'UTTAR PRADESH',
        '10' => 'BIHAR',
        '11' => 'SIKKIM',
        '12' => 'ARUNACHAL PRADESH',
        '13' => 'NAGALAND',
        '14' => 'MANIPUR',
        '15' => 'MIZORAM',
        '16' => 'TRIPURA',
        '17' => 'MEGHLAYA',
        '18' => 'ASSAM',
        '19' => 'WEST BENGAL',
        '20' => 'JHARKHAND',
        '21' => 'ODISHA',
        '22' => 'CHHATTISGARH',
        '23' => 'MADHYA PRADESH',
        '24' => 'GUJARAT',
        '25' => 'DAMAN AND DIU',
        '26' => 'DADRA AND NAGAR HAVELI',
        '27' => 'MAHARASHTRA',
        '28' => 'ANDHRA PRADESH(BEFORE DIVISION)',
        '29' => 'KARNATAKA',
        '30' => 'GOA',
        '31' => 'LAKSHWADEEP',
        '32' => 'KERALA',
        '33' => 'TAMIL NADU',
        '34' => 'PUDUCHERRY',
        '35' => 'ANDAMAN AND NICOBAR ISLANDS',
        '36' => 'TELANGANA',
        '37' => 'ANDHRA PRADESH (NEW)',
        '38' => 'Ladakh',
        '97' => 'OTHER TERRITORY',
        '96' => 'OTHER COUNTRY'
    ],
    'report_per_page' => '2500',
    'sales_types' => [
        /* 'Sale' => 'Sale',
        'JobWork' => 'JobWork', */
        'Domestic' => "Domestic",
        'Export' => "Export",
        /* 'ExportWithTax' => "Sales under GST 0.10%" */
    ],
    
    'payment_mode' => [
        'Cash' => 'Cash',
        'Cheque' => 'Cheque',
        'NEFT/RTGS' => 'NEFT/RTGS',
    ],

    'processes' => [
        'Grinding' => 'Grinding',
        'Printing' => 'Printing',
        'Packing' => 'Packing',
    ],
    'business_nature' => [
        'Manufacture' => 'Manufacture',
        'Trading' => 'Trading',
        'Service' => 'Service'
    ],
    'classification' => [
        'Micro' => 'Micro',
        'Small' => 'Small',
        'Medium' => 'Medium'
    ],

];
